spring.application.name=de-olho-na-camara-bff
logging.level.org.springframework.web.cors=DEBUG

camara-deputados.api.base-url=https://dadosabertos.camara.leg.br/api/v2/
camara-deputados.api.timeout=10s

# Database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=lImQSPlw6V
spring.datasource.url=jdbc:postgresql://postgres-ag-br1-05.hospedagemelastica.com.br:54157/nhajaz_abreolhod
spring.datasource.username=nhajaz_camaradev

# JWT configuration
jwt.expiration.ms=86400000
jwt.expiration.hours=1
jwt.secret=supersecretkey

domain.url=https://seusite.com

# Swagger configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs.yaml

# Compression configuration for SDUI endpoints
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml+rss,application/atom+xml,image/svg+xml
server.compression.min-response-size=1024

api.camara.base-url=https://dadosabertos.camara.leg.br/api/v2/

# Period (in months) used by the propositions sync job to compute dataApresentacaoInicio
# Example: 1 => first day of the previous month until today
sync.propositions.period.months=1

# Number of days to look back when syncing recent propositions and tramitations
proposition.recent.sync.days=3
